#if !canImport(ObjectiveC)
import XCTest

extension PromiseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PromiseTests = [
        ("testFinally", testFinally),
        ("testFinallyWithCatch", testFinallyWithCatch),
        ("testTransform", testTransform),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PromiseTests.__allTests__PromiseTests),
    ]
}
#endif
