#if !canImport(ObjectiveC)
import XCTest

extension PromiseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PromiseTests = [
        ("test_finally", test_finally),
        ("test_finally_with_catch", test_finally_with_catch),
        ("test_transform", test_transform),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PromiseTests.__allTests__PromiseTests),
    ]
}
#endif
